# Skip build process since we're deploying pre-built files
[build]
  publish = "dist"
  command = "echo 'No build needed - files are pre-built'"

# Environment variables for Supabase (set these in Netlify dashboard)
# [build.environment]
#   VITE_SUPABASE_URL = "https://your-project-id.supabase.co"
#   VITE_SUPABASE_ANON_KEY = "your-anon-key-here"

# SPA routing - redirects any path to index.html so React Router can handle routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers for enhanced protection
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://*.supabase.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co wss://*.supabase.co; font-src 'self' data:;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API routes caching
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=3600" 